### ISSUE TITLE
[1.18.1] Builder Quarry (any card) won't quarry bellow height 0

### ISSUE THREAD

**Issue by Ahkronn** [McJtyMods/RFToolsBuilder#79]
Tried several ways to achieve this, from settings on card to even move the builder block to the height 0 and start from there, but as soon as it reaches height 0 (deepslate zone) it just stops as "finished".
There's also seems to be an issue with the preview blocks not getting removed when preview is disabled.

**Comment by McJty** [comment]
I'll check it out.

**Comment by McJty** [comment]
The preview blocks go away for me if I press the preview button. Not sure why it's not working for you

**Comment by McJty** [comment]
The height limit has been fixed in latest release. Haven't been able to reproduce the support block issue

**Comment by trogarus** [comment]
Having this issue with 1-18-1 and latest mod and forge builds. It will quarry below 0, but only to around -56 and not fully to -65 overworld height, No offset. Only allows range of 256 still in card config slots. Cylinder shape is proper cylinder but not mining fully to bedrock level. Also the pump, not clearing, is still not removing all the liquids in overworld leaving many sources behind, and is NOT placing dirt like it used to.
